# Generated by Django 4.2.5 on 2023-10-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='height',
            new_name='size',
        ),
    ]
