# Generated by Django 4.2.5 on 2023-10-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
        ('users', '0003_create_accounts'),
    ]

    operations = [
    ]
