# Generated by Django 4.2.5 on 2023-10-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_thumbnailsize_plan_alter_customer_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='plan',
            new_name='account',
        ),
    ]
